
# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    #<added by Seba>
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    
    role_hierarchy:        
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    #</added by Seba>

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        #added by Seba
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    Cp6SZx4hhNc8YAYS:
                        password: 5ajLQs59zzfjJaBA
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        scheduler_secured_area:
            pattern: /6pGmCndfSy9Km6uV/4UEXNQxRstDqB65Q
            provider: in_memory
            http_basic: ~
                
        main:
            #commented by Seba
            #anonymous: ~
            #<added by Seba>
            pattern: ^/
            oauth:
                failure_path: /rentme?login
                login_path: /rentme?login
                check_path: /connect_check
                provider: fos_userbundle                                                
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                oauth_user_provider:
                    service: app.provider.oauth
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                default_target_path: /loggedIn
                always_use_default_target_path: true

            logout:       true
            anonymous:    true
            #</added by Seba>
            
            
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    #<added by Seba>
    access_control:
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rentme, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/vermietung, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/provider, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/dashboard, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/booking/response, role: IS_AUTHENTICATED_REMEMBERED }
        
        
        
        
    #</added by Seba>

