# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
            
    #<added by Seba>
    app.provider.oauth:
        class: AppBundle\Security\Core\User\OAuthUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebookID, google: googleID}]
        
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
            
    app.custom_fos_user_mailer:
        class: AppBundle\Mailer\HeyrentmeMailer
        arguments: [%mailer_fromEmail%, @router, @templating, @mailer,{ resetting.template: %fos_user.resetting.email.template%, mailer_app_url_prefix: %mailer_app_url_prefix%, admin_email: %admin_email% }]
        
    form_einstellungen:
        class: AppBundle\Form\EinstellungenType
        tags:
         -  { name: form.type, alias: form_einstellungen  }
    #</added by Seba>
    
    app.general_mailer:
        class: AppBundle\Mailer\GeneralMailer
        arguments: ['@mailer', '@templating', '@router', @doctrine.orm.entity_manager , { mailer_fromEmail: %mailer_fromemail%, mailer_fromName: %mailer_fromname%, mailer_app_url_prefix: %mailer_app_url_prefix%, notification_email: %notification_email%  } ]
    
    scheduler:
        class: AppBundle\Service\SchedulerService
        arguments: [@doctrine.orm.entity_manager, @mailer, @templating, @monolog.logger.scheduler, @router, { mailer_app_url_prefix: %mailer_app_url_prefix%, mailer_fromemail: %mailer_fromemail%, mailer_fromname: %mailer_fromname%, image_storage_dir : %image_storage_dir% }]

    thumbnail:
        class: AppBundle\Service\ThumbnailService
        arguments: [@doctrine.orm.entity_manager, @monolog.logger, { image_storage_dir : %image_storage_dir% }]
        
    filluuid:
        class: AppBundle\Service\FillUuidService
        arguments: [@doctrine.orm.entity_manager]
        
    convert_talent_to_tariff:
        class: AppBundle\Service\ConvertTalentToTariff
        arguments: [@doctrine.orm.entity_manager]
