<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Filesystem\Filesystem;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{    
    public function getAllOrderedByPosition() {
        $q = "select c from AppBundle:Blog c order by c.position asc";
        return $this->getEntityManager()->createQuery($q)->getResult();
    }
    
    public function getPostForEquipmentPage() {
        $q = "select b from AppBundle:Blog b order by b.position, b.createdAt asc";
        return $this->getEntityManager()->createQuery($q)->setMaxResults(1)->getOneOrNullResult();
    }
    
    public function getByPosition($position) {
        $q = "select b from AppBundle:Blog b where b.position = :position";
        return $this->getEntityManager()->createQuery($q)->setParameter('position', $position)->getOneOrNullResult();
    }
    
    public function getBySlug($slug) {
        $dql = 'select b from AppBundle:Blog b where b.slug = :slug';
        return $this->getEntityManager()->createQuery($dql)->setParameter(':slug', $slug)->getOneOrNullResult();
    }
    
    public function countAll() {
        return $this->createQueryBuilder('c')
            ->select('count(c.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
    
    public function cleanCurrentSelection($blogId) {
        $q = "delete from AppBundle:BlogRelated br where br.blog = :blogId";
        $this->getEntityManager()->createQuery($q)->setParameter('blogId', $blogId)->execute();
    }
   
    
    public function getForRelatedOrderedByName($id) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        // build query
        $qb->select('b')
           ->from('AppBundle:Blog', 'b')     
           ->where($qb->expr()->neq('b.id', $id))
           ->orderBy("b.title", 'asc');      
        $q = $qb->getQuery();
        
        return $q->getResult();        
    }
    
    public function getGridOverview($sortColumn, $sortDirection, $pageSize, $page) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        // build query
        $qb->select('b')
            ->from('AppBundle:Blog', 'b');
        // sort by
        if (!empty($sortColumn)) {
            if (!empty($sortDirection)) {
                $qb->orderBy($sortColumn, $sortDirection);
            }
            else {
                $qb->orderBy($sortColumn);
            }
        }

        $q = $qb->getQuery();
        // page and page size
        if (!empty($pageSize)) {
            $q->setMaxResults($pageSize);
        }
        if (!empty($page) && $page != 1) {
            $q->setFirstResult(($page - 1) * $pageSize);
        }
        return $q->getResult();        
    }
    
    public function isSlugUnique($slug, $blogId = null) {
        $dql = 'select count(b.id) from AppBundle:Blog b where b.slug = :slug';
        if ($blogId != null) {
            $dql = $dql . ' and b.id != :blogId';
        }
        $q = $this->getEntityManager()->createQuery($dql);
        $q->setParameter(':slug', $slug);
        if ($blogId != null) {
            $q->setParameter(':blogId', $blogId);
        }
        return $q->getSingleScalarResult() == 0;
    }
    public function getAllThumbnailless() {
        $dql = <<<EOT
            select b, i
            from AppBundle:Blog b
                join b.image i
            where i.thumbnailPath is null
EOT;
        return $this->getEntityManager()->createQuery($dql)->getResult();
    }
    
    public function getOneByUuid($uuid) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        /*
         * Please not this query uses "fetch join".
         * It fetches images and discounts (associated with equipments) immediately 
         * (instead of lazy loading them later).
         * Keep for optimum performance.
         */        
        $qb->select('b') // this line forces fetch join
            ->from('AppBundle:Blog', 'b');
        
        //$qb->andWhere("e.status = ". Equipment::STATUS_APPROVED);
        //$qb->andWhere('u.status = '. User::STATUS_OK);
        $qb->andWhere($qb->expr()->eq('b.uuid', ':uuid'));
        
        $b = null;
        try {
            $q = $qb->getQuery();
            $q->setParameter(':uuid', "{$uuid}");
            $b = $q->getSingleResult();
        } catch (NoResultException $e) {}
       
        return $b;
    }
    public function getAllWithoutUuid() {
        $sql = <<<EOT
            select b
            from AppBundle:Blog b
            where b.uuid is null
EOT;
        return $this->getEntityManager()->createQuery($sql)->getResult();
    }
}
