<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Filesystem\Filesystem;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRelatedRepository extends EntityRepository
{    
    public function cleanCurrentSelection($blogId) {
        $q = "delete from AppBundle:BlogRelated br where br.blogId = :blogId";
        $this->getEntityManager()->createQuery($q)->setParameter('blogId', $blogId)->execute();
    }
}
