<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountCodeRepository extends EntityRepository
{    
   
    public function countAll() {
        return $this->createQueryBuilder('dc')
            ->select('count(dc.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
    
    public function getGridOverview($sortColumn, $sortDirection, $pageSize, $page) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        // build query
        $qb->select(array('dc', 'u'))
            ->from('AppBundle:DiscountCode', 'dc')
                 ->leftJoin('dc.user', 'u');
        // sort by
        if (!empty($sortColumn)) {
            if (!empty($sortDirection)) {
                $qb->orderBy($sortColumn, $sortDirection);
            }
            else {
                $qb->orderBy($sortColumn);
            }
        }

        $q = $qb->getQuery();
        // page and page size
        if (!empty($pageSize)) {
            $q->setMaxResults($pageSize);
        }
        if (!empty($page) && $page != 1) {
            $q->setFirstResult(($page - 1) * $pageSize);
        }
        return $q->getResult();        
    }
 
    public function assignToUser($user) {
        // find a free discount code
        $dql = sprintf("select dc from AppBundle:DiscountCode dc where dc.status = %d",
                DiscountCode::STATUS_NEW);
        $q = $this->getEntityManager()->createQuery($dql);
        $q->setMaxResults(1);
        $rows = $q->getResult();
        
        if (count($rows) == 0) {
            return null;
        } 
        $code = $rows[0];
        
        // assign to the user
        $code->setUser($user);
        $code->setStatus(DiscountCode::STATUS_ASSIGNED);
        $this->getEntityManager()->flush();
        
        return $code;
    }
}
