<?php

namespace AppBundle\Entity;

/**
 * InquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentQuestionRepository extends \Doctrine\ORM\EntityRepository {

}

