<?php

namespace AppBundle\Entity;

/**
 * EquipmentFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentFeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
