<?php

namespace AppBundle\Entity;

/**
 * InquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InquiryRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateInquiries($user) {
        $dql = "update AppBundle:Inquiry i set i.user = :userId where i.email = :email";
        $q = $this->getEntityManager()->createQuery($dql);
        $q->setParameter(':userId', $user->getId());
        $q->setParameter(':email', $user->getEmail());
        $q->execute();        
    }
}
