<?php

namespace AppBundle\Entity;

use AppBundle\Utils\SearchParams;
use Doctrine\ORM\EntityRepository;

/**
 * TalentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalentRepository extends EntityRepository
{
    public function getAllBySubcategory($subcategoryId) {
        $sql = "select e from AppBundle:Talent e where e.subcategory = :subcategoryId and e.status = :approved";
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter('subcategoryId', $subcategoryId);
        $query->setParameter('approved', Talent::STATUS_APPROVED);
        return $query->getResult();        
    }   
    
    public function getAllForOtherCategories($subcategoryId) {
        $sql = "select e from AppBundle:Talent e where e.subcategory != :subcategoryId and e.status = :approved";
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter('subcategoryId', $subcategoryId);
        $query->setParameter('approved', Talent::STATUS_APPROVED);
        return $query->setMaxResults(4)->getResult();        
    }   
    
    public function getSamplePreviewTalentsBySubcategory($subcategoryId, $eqId) {
        #TODO: Correct query, remove hardcoded number of items
        // TODO: refactor: write query with proper "order by" and take first four items
        $sql = "select e from AppBundle:Talent e where e.subcategory = :subcategoryId and e.id != :id and e.status = :approved";
        $query = $this->getEntityManager()->createQuery($sql);
        $query->setParameter('subcategoryId', $subcategoryId);
        $query->setParameter('id', $eqId);
        $query->setParameter('approved', Talent::STATUS_APPROVED);        
        $results = $query->setMaxResults(4)->getResult();        
        
        if (count($results) < 4) {
            $resultsFromOtherCats = $this->getAllForOtherCategories($subcategoryId);
            foreach($resultsFromOtherCats as $rfoc){
                $results[count($results)] = $rfoc;
                if (count($results) == 4) {
                    break;
                }
            }
        }
        
        return $results;
    }   
    
    public function getAllByUserId($userId) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('e')
            ->from('AppBundle:Talent', 'e')
            ->join('e.user', 'u');
        $qb->andWhere("u.id = {$userId}");

        $q = $qb->getQuery();
        
        return $q->getResult();        
    }
    
    public function getGridOverview($sortColumn, $sortDirection, $pageSize, $page, $sStatus) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        // build query
        $qb->select('e, u')
            ->from('AppBundle:Talent', 'e')
            ->join('e.user','u');
        
        if (!empty($sStatus)) {
            $qb->andWhere($qb->expr()->eq('e.status', ':status'));
        }
        
        // sort by
        if (!empty($sortColumn)) {
            if (!empty($sortDirection)) {
                $qb->orderBy($sortColumn, $sortDirection);
            }
            else {
                $qb->orderBy($sortColumn);
            }
        }

        $q = $qb->getQuery();
        if (!empty($sStatus)) {
            $q->setParameter(':status', $sStatus);
        }
        
        // page and page size
        if (!empty($pageSize)) {
            $q->setMaxResults($pageSize);
        }
        if (!empty($page) && $page != 1) {
            $q->setFirstResult(($page - 1) * $pageSize);
        }
        return $q->getResult();        
    }
    
    public function countAll() {
        return $this->createQueryBuilder('e')
            ->select('count(e.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
    
    /*
    public function getAll($categoryId = null) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('e')
            ->from('AppBundle:Talent', 'e')
            ->join('e.subcategory', 's');
        if ($categoryId != null) {
            $qb->andWhere("s.category = {$categoryId}");
        }
        
        $q = $qb->getQuery();
        return $q->getResult();
    }
    */
    public function getAll(SearchParams $params) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        /*
         * Please not this query uses "fetch join".
         * It fetches images and discounts (associated with talents) immediately 
         * (instead of lazy loading them later).
         * Keep for optimum performance.
         */        
        $qb->select('e', 'i', 'd') // this line forces fetch join
            ->from('AppBundle:Talent', 'e')
            ->join('e.subcategory', 's')
            ->leftJoin('e.images', 'i')
            ->leftJoin('e.discounts', 'd');
        
        $qb->andWhere("e.status = ". Talent::STATUS_APPROVED);
        
        if ($params->getCategoryId() != null) {
            $qb->andWhere("s.category = {$params->getCategoryId()}");
        }
        if ($params->getDiscount()) {
            $now = date('Y-m-d H:i:s');
            $qb->andWhere("d.createdAt <= '{$now}'")
                ->andWhere("d.expiresAt >= '{$now}'");
        }
        if ($params->getTestBuy()) {
            $qb->andWhere('e.priceBuy > 0');
        }
        if ($params->getSort() === 'date') {
            $qb->orderBy('e.createdAt', 'desc');
        }
        elseif ($params->getSort() === 'price') {
            $qb->orderBy ('e.price', 'asc');
        }
        
        $q = $qb->getQuery();
        return $q->getResult();
    }
    
    public function clearFeatures($talentId) {
        $sql = 'delete from AppBundle:TalentFeature ef where ef.talent = :talent';
        $q = $this->getEntityManager()->createQuery($sql);
        $q->setParameter(':talent', $talentId);
        $q->execute();
    }
    public function saveFeatures($talentId, $features) {
        $this->clearFeatures($talentId);
        $em = $this->getEntityManager();
        foreach ($features as $id => $text) {
            $ef = new TalentFeature();
            $ef->setTalent($em->getReference('AppBundle:Talent', $talentId));
            $ef->setFeature($em->getReference('AppBundle:Feature', $id));
            $ef->setName($text);
            $em->persist($ef);
        }
        $em->flush();
        $em->clear();
    }
    public function getFeaturesAsArray($talentId) {
        $sql = "select * from talent_feature where talent_id = {$talentId}";
        $conn = $this->getEntityManager()->getConnection();
        $rows = $conn->query($sql)->fetchAll();
        $conn->close();
        
        $result = array();
        foreach ($rows as $row) {
            $result[$row['feature_id']] = $row['name'];
        }
        
        return $result;
    }
    public function getTalentFeatures($talentId) {
        /*
         * ef = talent_feature
         * f = feature
         */
        $dql = <<<EOT
                select e, ef, f, fs
                from AppBundle:Talent e
                    join e.features ef
                    join ef.feature f
                    join f.featureSection fs
                where e.id = :talentId
                order by fs.position asc, f.position asc
EOT;
        $q = $this->getEntityManager()->createQuery($dql);
        $q->setParameter(':talentId', $talentId);
        $eqs = $q->getResult();
        
        if (count($eqs) == 0) {
            return array();
        }
        
        $fts = array();
        $eq = $eqs[0];
        
        // iterate over features and assemble array        
        foreach ($eq->getFeatures() as $ef) {               // ef = talent_feature
            $fs = $ef->getFeature()->getFeatureSection();   
            $name = $fs->getName();                         // feature_section name becomes array's key
            if (!array_key_exists($name, $fts)) {
                $fts[$name] = array();
            }
            if ($ef->getName() !== null) {                  // array of selected features becomes array's value
                $val = $ef->getName();
            } else {
                $val = $ef->getFeature()->getShortname();   
            }
            array_push($fts[$name], $val);
        }
        foreach ($fts as $key => $val) {                    // translate array of values into a string (comma-separated)
            $fts[$key] = implode(', ', $val);
        }
        return $fts;
    }

    /* score */
    public function addRating($talentRating) {
        $em = $this->getEntityManager();
        $em->persist($talentRating);
        $em->flush();
        $this->updateScore($talentRating->getTalent()->getId());
    }
    public function updateScore($talentId) {
        $sql = <<<EOT
            update talent
            set rating = (
                    select avg(rating)
                    from talent_rating
                    where talent_id = {$talentId}
            )
            where id = {$talentId}
EOT;
        $conn = $this->getEntityManager()->getConnection();
        $conn->exec($sql);
        $conn->close();        
    }
    
}
