<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Filesystem\Filesystem;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonialRepository extends EntityRepository
{    
    
    public function countAll() {
        return $this->createQueryBuilder('t')
            ->select('count(t.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
    
    public function getGridOverview($sortColumn, $sortDirection, $pageSize, $page) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        // build query
        $qb->select('t')
            ->from('AppBundle:Testimonial', 't');
        // sort by
        if (!empty($sortColumn)) {
            if (!empty($sortDirection)) {
                $qb->orderBy($sortColumn, $sortDirection);
            }
            else {
                $qb->orderBy($sortColumn);
            }
        }

        $q = $qb->getQuery();
        // page and page size
        if (!empty($pageSize)) {
            $q->setMaxResults($pageSize);
        }
        if (!empty($page) && $page != 1) {
            $q->setFirstResult(($page - 1) * $pageSize);
        }
        return $q->getResult();        
    }
    
    public function getForMainPage($maxResults) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        // build query
        $qb->select('t')
            ->from('AppBundle:Testimonial', 't')
            ->orderBy("t.position");
       
        $q = $qb->getQuery();
        // page and page size
        
        if ($maxResults != 0)
            $q->setMaxResults($maxResults);
        
        return $q->getResult();        
    }
    
}
